name: astrox
channels:
- conda-forge
- defaults
dependencies:
- numpy
- jupyter
- matplotlib
- scikit-learn=0.23.2
- scipy
- pandas
- seaborn
- statsmodels
- jupyter_contrib_nbextensions
- yellowbrick
- astropy